@startuml

' Config ERD diagram
hide circle
skinparam linetype ortho

entity packages {
    *id: integer <<generated>>
    ---
    namespace: varchar
    name: varchar
    version: varchar
}

entity scans {
    *id: integer <<generated>>
    ---
    package_id: integer
    created: timestamp
    location: clob
    license: clob
    error: clob
}

packages ||--o{ scans
@enduml
