ALTER TABLE scans
    ADD COLUMN uuid UUID NOT NULL DEFAULT random_uuid();
ALTER TABLE scans
    ADD COLUMN contested BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE scans
    ADD COLUMN confirmed BOOLEAN NOT NULL DEFAULT FALSE;
