name: Java CI with Gradle

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: [self-hosted, research] 
    container: python:3.8
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
    - name: Install scancode 
      run: pip install scancode-toolkit[full]
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build -x test
    - name: Tests
      run: ./gradlew test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        comment_title: Unit Test Statistics
        hide_comments: all but latest
        comment_on_pr: true
        files: build/test-results/**/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false
