name: Java CI with Gradle

on:
  push:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software

jobs:
  build-and-test:
    name: Build gradle project 

    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.6
        with:
          path: | 
            build/test-results/**/*.xml
            build/libs/*.jar
          key: license-scanner-${{ github.sha }}

      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'

      - name: Setup python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: '3.9' 

      - name: Install scancode 
        run: |
          pip install -r docker/requirements.txt
          scancode --version
          extractcode --version
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x test

      - name: Tests
        run: ./gradlew test

  create-docker-image:
    name: "Create docker image"
    needs: build-and-test
    runs-on: ubuntu-latest 
    # Don't publish when build is skipped
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.6
        with:
          path: | 
            build/test-results/**/*.xml
            build/libs/*.jar
          key: license-scanner-${{ github.sha }}

      - name: Build Docker Images
        uses: philips-software/docker-ci-scripts@v3.3.2
        with:
          dockerfile: docker/Dockerfile
          image-name: license-scanner 
          tags: 0 0.6 0.6.0 v0.6.0 latest

