name: Get Licenses in SPDX

on:
  push:
    branches:
      - develop
      - master
      - forest-ci-license-scan

jobs:
  scan:
    runs-on: [self-hosted, research]
    steps:
      - name: Clone code repository
        uses: actions/checkout@v2
      - name: Clone forest ci repository
        uses: actions/checkout@v2
        with:
          repository: philips-internal/forest-ci
          path: .forest
          ref: develop 
          ssh-key: ${{ secrets.FOREST_CI_REPO_SSH_KEY }}
      - name: Setup Java 11.0.1 
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.1'
      - name: Create spdx-file
        id: license-scanner 
        uses: ./.forest/actions/reports/spdx
        with:
          project: bom-bar 
      - name: Show output filename
        run: |
          echo ${{ steps.spdx-builder.outputs.spdx-file }}
      - name: Upload file to build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: licenses
          path: ${{ steps.spdx-builder.outputs.spdx-file }}
